name: widgetbook_workspace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  widgetbook_annotation: ^3.2.0
  widgetbook: ^3.10.0
  device_frame: ^1.2.0
  flutter_screenutil: ^5.9.3
  reactive_forms: ^16.1.1

  widgetbook_demo:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  widgetbook_generator: ^3.9.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
